package dev.goquick.kmpgradlebuilder

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

abstract class GenerateKmpProfilesTask : DefaultTask() {

    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val className: Property<String>

    @get:Input
    abstract val message: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val pkg = packageName.get()
        val cls = className.get()
        val msg = message.get()

        val targetDir = outputDirectory.get().dir(pkg.replace('.', '/')).asFile
        targetDir.mkdirs()

        val file = targetDir.resolve("$cls.kt")
        val escapedMessage = msg.replace("\"", "\\\"")
        file.writeText(
            """
            |// Generated by dev.goquick.kmpgradlebuilder at ${java.time.Instant.now()}
            |package $pkg
            |
            |class $cls {
            |    companion object {
            |        const val MESSAGE: String = "$escapedMessage"
            |    }
            |}
            |
            """.trimMargin()
        )
    }
}
